# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

# --- 核心配置：根据你的项目修改 ---
title = "一个计科金融大学生的浅显思考"
baseURL = "https://ApolloMonasa.github.io/"

# --- 主题和语言配置：保持不变 ---
theme = [
  "FixItsDoc",
  "FixIt",
  "shortcode-docs-bookmark"
]
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
hasCJKLanguage = true

# --- 功能开关和构建选项：保持默认推荐值 ---
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# 忽略一些不影响构建的小错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken", 'warning-dev-version']

[outputs]
    home = ["html", "rss", "archives", "offline", "search", "json"] # 确保 RSS 和 JSON Feed 开启，便于订阅和被其他服务抓取

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
