# -------------------------------------------------------------------------------------
# Menu Configuration
# 优化后的版本
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "neoforge"
  name = "NeoForge开发教程"
  url = "/docs/neoforge/简介"  # [修正] 指向教程的根目录，而不是具体页面
  title = "NeoForge 模组开发教程"
  weight = 10              # [修正] 使用唯一的 weight，并留出间隔

[[main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  title = "浏览所有文章"
  weight = 20              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-pen-nib" # [建议] 为“文章”添加图标

[[main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  title = "按时间归档"
  weight = 30              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-archive"

[[main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  title = "按分类浏览"
  weight = 40              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  title = "按标签浏览"
  weight = 50              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "portfolio"
  name = "作品集"
  url = "/portfolio/"
  title = "查看我的作品集"
  weight = 60              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-folder-open" # [建议] 为“作品集”添加图标