# -------------------------------------------------------------------------------------
# Menu Configuration
# 优化后的版本
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "neoforge"
  name = "NeoForge开发教程"
  url = "/docs/neoforge/0Introduction"  # [修正] 指向教程的根目录，而不是具体页面
  title = "NeoForge 模组开发教程"
  weight = 10              # [修正] 使用唯一的 weight，并留出间隔
  [main.params]
    icon = "fa-solid fa-code" # [修改] 为NeoForge教程添加了代码图标

[[main]]
  identifier = "posts"
  name = "金融学"
  url = "/docs/finance/0introduction"
  title = "浏览金融学文章"
  weight = 20              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-pen-nib" # [建议] 为“文章”添加图标

[[main]]
  identifier = "reading-notes"
  name = "读书随笔"
  url = "/posts/0intro/" # 注意：这里使用了相对路径，这是 Hugo 的标准做法
  title = "浏览读书随笔"
  weight = 25              # [新增] 插入到金融学(20)和归档(30)之间
  [main.params]
    icon = "fa-solid fa-book-open" # [新增] 为读书随笔添加了打开的书本图标

[[main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  title = "按时间归档"
  weight = 30              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-archive"

[[main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  title = "按分类浏览"
  weight = 40              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  title = "按标签浏览"
  weight = 50              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "portfolio"
  name = "作品集"
  url = "/portfolio/"
  title = "查看我的作品集"
  weight = 60              # [修正] 唯一的 weight
  [main.params]
    icon = "fa-solid fa-folder-open" # [建议] 为“作品集”添加图标