# -------------------------------------------------------------------------------------
# 主题核心配置文件 (params.toml)
# 官方文档: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------
customJS = ["/js/custom.js"]
# FixIt 主题版本，建议保持默认，除非您手动升级了主题。
version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
# 网站描述，非常重要！会显示在浏览器标签页的副标题和搜索引擎结果中。
description = "个人博客，包括但不限于算法竞赛，Minecraft模组开发，计科相关内容，学习思想日志。"
# 网站关键词，用逗号分隔，有助于搜索引擎优化 (SEO)。
keywords = ["Minecraft", "模组开发", "NeoForge", "教程", "中文", "算法竞赛"]
# 网站默认主题颜色，"auto" 表示跟随操作系统设置，可选 "light", "dark"。
defaultTheme = "auto"
# 指纹加密算法，用于确保浏览器加载的 CSS/JS 资源未被篡改。留空即可。
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# 日期格式，"2006-01-02" 是 Go 语言的特殊写法，代表 YYYY-MM-DD。
dateFormat = "2006-01-02"
# 网站分享预览图（例如分享到微信、Twitter 时显示的图片）。暂时可以留空。
images = []
# 是否启用 PWA (渐进式 Web 应用)，允许用户将网站“安装”到桌面。初期可以禁用。
enablePWA = false
# 是否为外部链接（指向其他网站的链接）自动添加一个特殊图标。
externalIcon = false
# 是否自动将文章标题的首字母大写。
capitalizeTitles = true
# 是否在每个页面的标题后面都追加上网站的全局标题（在 hugo.toml 中设置的 title）。
withSiteTitle = true
# 追加网站标题时使用的分隔符，例如 "页面标题 - 网站标题"。
titleDelimiter = "-"
# 是否在首页的标题中也追加副标题。
indexWithSubtitle = false
# 是否将文章摘要显示为纯文本（去掉 Markdown 格式）。
summaryPlainify = false
# 是否在网页头部注入主题信息元标签。建议保留以支持主题作者，设为 false 可关闭。
disableThemeInject = false

# --- 作者信息配置 ---
[author]
  # 你的名字或昵称。
  name = "ApolloMonasa"
  # 你的联系邮箱。
  email = "apollomonasa@gmail.com"
  # 点击名字后跳转的链接，通常是你的 GitHub 主页。
  link = "https://github.com/ApolloMonasa"
  # 头像图片地址。如果为空，会尝试使用 Gravatar 获取头像。这里已填好你的链接。
  avatar = "https://i.ooxx.ooo/i/NTYyY.png"

# --- Git 仓库信息 (用于“编辑此页”、“报告问题”等功能) ---
# 强烈建议配置此项，方便读者贡献和反馈。
[gitInfo]
  # 你的公开Git仓库地址。
  repo = "https://github.com/ApolloMonasa/Minecraft-Modding-Tutorial-For-NeoForge"
  # 你的主分支名称。
  branch = "main"
  # Markdown 文件所在的目录，相对于仓库根目录。
  dir = "content"
  # "报告问题" 按钮的链接模板。保持默认即可。
  # available template params: {title} {URL} {sourceURL}
  issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"

# --- App 图标配置 (当网站被添加到手机主屏幕时使用) ---
[app]
  # 添加到主屏幕时显示的名字。
  title = "Apollo ans wmsnp's Blogs"
  # 是否不生成 favicon 图标链接。
  noFavicon = false
  # SVG 格式的 favicon。
  svgFavicon = "https://i.ooxx.ooo/i/ZDQ0N.png"
  # Safari 浏览器标签页固定时的图标颜色。
  iconColor = "#5bbad5"
  # Windows 磁贴颜色。
  tileColor = "#da532c"
  # Android 浏览器顶部的主题颜色。
  [app.themeColor]
    light = "#f8f8f8"
    dark = "#252627"

# --- 网站内搜索配置 ---
# 默认使用 fuse.js 进行前端本地搜索，效果不错，建议保持默认。
[search]
  enable = true
  # 搜索引擎类型 ["algolia", "fuse"]
  type = "fuse"
  # 内容分块的最大索引长度。
  contentLength = 4000
  # 搜索框的占位文本。
  placeholder = ""
  # 显示结果的最大数量。
  maxResultLength = 10
  # 搜索结果摘要的长度。
  snippetLength = 30
  # 搜索结果高亮部分的 HTML 标签。
  highlightTag = "em"
  # 索引是否使用绝对路径 URL。
  absoluteURL = false
  # 如果你使用 Algolia 搜索服务，在这里配置。
  [search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  # Fuse.js 的高级搜索选项，通常无需修改。
  [search.fuse]
    # FixIt 0.2.17 | NEW https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# --- 页面顶部导航栏配置 ---
[header]
  # 桌面端导航栏模式: "sticky" (吸顶), "normal" (不吸顶), "auto" (自动)。
  desktopMode = "sticky"
  # 移动端导航栏模式。
  mobileMode = "auto"
  # 导航栏左侧的 Logo 和标题。
  [header.title]
    # Logo 图片的路径。建议准备一个，放在项目的 static/images/ 目录下。
    # 示例: logo = "/images/my-logo.png"
    # 这里我帮你移除了旧的路径，留空会显示下面的文字标题。
    logo = "https://i.ooxx.ooo/i/ZDQ0N.png"
    # 如果没有 Logo，会显示的文字标题。
    name = "Apollo and wmsnp's Blogs"
    # 可以在标题前添加额外内容（支持HTML），比如图标。
    pre = ""
    # 可以在标题后添加额外内容（支持HTML）。
    post = ""
    # 是否开启标题的打字机动画效果。
    typeit = false
  # 导航栏副标题。
  [header.subtitle]
    # 副标题内容。
    name = ""
    # 是否开启副标题的打字机动画效果。
    typeit = false

# --- 面包屑导航 (显示当前页面路径，如：主页 > 教程 > 第一章) ---
[breadcrumb]
  # 教程类网站强烈建议开启。
  enable = true
  # 是否吸顶。
  sticky = false
  # 是否显示 "主页" 链接。
  showHome = true
  # 分隔符。
  separator = "/"
  # 路径首字母是否大写。
  capitalize = true

# --- 文章底部的“上一篇/下一篇”导航 ---
[navigation]
  # 是否只在同一分类下显示导航。教程站建议开启。
  inSection = true
  # 是否反转“上一篇”和“下一篇”的顺序。
  reverse = false

# --- 页脚配置 ---
[footer]
  enable = true
  # 是否显示版权信息 ©
  copyright = true
  # 是否显示作者名字
  author = true
  # 网站起始年份
  since = 2025
  # 公安备案号（仅中国大陆）。
  gov = ""
  # ICP 备案号（仅中国大陆）。
  icp = ""
  # 授权协议 (支持 HTML)，默认的 CC BY-NC-SA 4.0 很好，建议保留。
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # 是否显示由 Hugo 和 FixIt 强力驱动。
  [footer.powered]
    enable = false
    hugoLogo = false
    themeLogo = false
  # 网站已运行时间。
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = "" # e.g. "2021-12-18T16:15:22+08:00"
  # 页脚各元素的显示顺序，数字越小越靠前。
  [footer.order]
    powered = 0
    copyright = 0
    statistics = 0
    visitor = 0
    beian = 0

# --- 归档页面配置 (所有文章的列表) ---
[archives]
  # 每页显示的文章数量。
  paginate = 20
  # 日期格式 (月-日)。
  dateFormat = "01-02"

# --- 分类列表页配置 ---
[section]
  # 每页显示的文章数量。
  paginate = 20
  # 日期格式 (月-日)。
  dateFormat = "01-02"
  # 分类列表的 RSS 源配置。
  [section.feed]
    # RSS 源中包含的文章数量, -1 表示所有。
    limit = -1
    # RSS 源中是否包含全文。
    fullText = false

# --- 标签列表页配置 ---
[list]
  # 每页显示的文章数量。
  paginate = 20
  # 日期格式 (月-日)。
  dateFormat = "01-02"
  # 标签列表的 RSS 源配置。
  [list.feed]
    # RSS 源中包含的文章数量, -1 表示所有。
    limit = -1
    # RSS 源中是否包含全文。
    fullText = false

# --- “最近更新”标识配置 ---
# 在指定天数内更新过的文章会显示一个“新”的标记。
[recentlyUpdated]
  archives = true
  section = true
  list = true
  days = 30 # 30天内更新的会显示
  maxCount = 10 # 最多显示10个

# --- 标签云页面配置 ---
[tagcloud]
  # 如果你的标签很多，可以开启此功能生成一个标签云页面。
  enable = true
  min = 14 # 最小字号 (px)
  max = 32 # 最大字号 (px)
  peakCount = 10 # 达到最大字号所需的文章数量
  orderby = "name" # 标签排序方式 ["name", "count"]

# --- 首页 (Home Page) 配置 ---
[home]
  # 个人信息卡片
  [home.profile]
    enable = true
    # 用于获取 Gravatar 头像的邮箱（如果下面的 avatarURL 为空）。
    gravatarEmail = "apollomonasa@gmail.com"
    # 直接指定一个头像图片的 URL (优先级不高于 gravatarEmail)。
    avatarURL = "https://i.ooxx.ooo/i/NTYyY.png"
    # 头像下方的菜单链接标识符。
    avatarMenu = ""
    # 首页大标题，如果留空，会使用 hugo.toml 里的网站标题。
    title = "Hi! I'm ApolloMonasa"
    # 首页副标题。
    subtitle = "Welcome To My Blog Site!"
    # 副标题是否使用打字机动画。
    typeit = true
    # 是否显示社交链接图标。
    social = true
    # 一段免责声明或欢迎语 (支持 HTML)。
    disclaimer = ""
  # 首页的文章列表。
  [home.posts]
    enable = true
    # 每页显示多少篇文章。
    paginate = 10

# --- 社交链接配置 ---
# 在下方填入你的社交媒体用户名或完整链接。留空则该图标不显示。
[social]
  GitHub = "ApolloMonasa"
  Bilibili = "1029459856" # 你的 Bilibili 用户 ID
  Zhihu = ""
  Discord = ""
  QQGroup = "1062064369" # 你的 QQ 群号或加群链接
  Email = "apollomonasa@gmail.com"
  RSS = false # 保持 true 以便订阅
  # --- 其他社交媒体 ---
  Linkedin = ""
  Twitter = ""
  Instagram = ""
  Facebook = ""
  Telegram = ""
  Medium = ""
  Gitlab = ""
  Youtubelegacy = ""
  Youtubecustom = ""
  Youtubechannel = ""
  Tumblr = ""
  Quora = ""
  Keybase = ""
  Pinterest = ""
  Reddit = ""
  Codepen = ""
  FreeCodeCamp = ""
  Bitbucket = ""
  Stackoverflow = ""
  Weibo = ""
  Odnoklassniki = ""
  VK = ""
  Flickr = ""
  Xing = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Bandcamp = ""
  Paypal = ""
  Fivehundredpx = ""
  Mix = ""
  Goodreads = ""
  Lastfm = ""
  Foursquare = ""
  Hackernews = ""
  Kickstarter = ""
  Patreon = ""
  Steam = ""
  Twitch = ""
  Strava = ""
  Skype = ""
  Whatsapp = ""
  Douban = ""
  Angellist = ""
  Slidershare = ""
  Jsfiddle = ""
  Deviantart = ""
  Behance = ""
  Dribbble = ""
  Wordpress = ""
  Vine = ""
  Googlescholar = ""
  Researchgate = ""
  Mastodon = ""
  Thingiverse = ""
  Devto = ""
  Gitea = ""
  XMPP = ""
  Matrix = ""
  ORCID = ""
  Liberapay = ""
  Ko-Fi = ""
  BuyMeaCoffee = ""
  Linktree = ""
  QQ = ""
  Diaspora = ""
  CSDN = "xyl6716"
  DiscordInvite = ""
  Lichess = ""
  Pleroma = ""
  Kaggle = ""
  MediaWiki= ""
  Plume = ""
  HackTheBox = ""
  RootMe = ""
  Feishu = ""
  TryHackMe = ""
  Douyin = ""
  TikTok = ""
  Credly = ""
  Phone = ""
  # 自定义社交链接的示例
  # [social.twitter]
  #   id = "lruihao"
  #   weight = 3
  #   prefix = "https://twitter.com/"
  #   Title = "Twitter"
  #   [social.twitter.icon]
  #     class = "fa-brands fa-x-twitter fa-fw"

# --- 打字机动画效果的全局配置 ---
[typeit]
  # 打字速度 (毫秒)
  speed = 100
  # 光标闪烁速度 (毫秒)
  cursorSpeed = 1000
  # 光标字符 (支持HTML)
  cursorChar = "|"
  # 打字结束后光标停留时间, -1 表示无限
  duration = -1
  # 是否循环播放动画
  loop = false

# --- Mermaid 图表配置 ---
[mermaid]
  # 可用的主题，详见 Mermaid.js 官网
  themes = ["default", "dark"]

# --- Admonition (提示框) 短代码的自定义图标 ---
# 语法: <类型> = "<FontAwesome 图标 class>"
[admonition]
  # ban = "fa-solid fa-ban"

# --- 任务列表的自定义图标 ---
# 语法: <符号> = "<FontAwesome 图标 class>"
[taskList]
  # tip = "fa-regular fa-lightbulb"

# --- [version] 短代码配置 ---
[repoVersion]
  # 发布版本的 URL 前缀
  url = "https://github.com/hugo-fixit/FixIt/releases/tag/v"
  # 项目名称
  name = "FixIt"

# --- 中文排版优化工具 PanguJS ---
# 自动在中文和英文/数字之间添加空格，强烈建议开启。
[pangu]
  # 是否启用
  enable = true
  # 生效的 HTML 元素选择器
  selector = "article"

# --- 水印功能 ---
[watermark]
  enable = false
  # 水印文字 (支持HTML)
  content = ""
  # 透明度
  opacity = 0.1
  # ... 其他水印样式设置

# --- 网站访问量统计 (Busuanzi) ---
[busuanzi]
  # 是否启用。如果启用，页脚会显示网站总访问量和页面阅读量。
  enable = false
  # Busuanzi 的 JS 文件源，国内可以用下面的镜像。
  # source = "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  source = "https://vercount.one/js"
  # 是否显示网站总访问量
  siteViews = true
  # 是否显示当前页面阅读量
  pageViews = true

# --- 各种搜索引擎的网站所有权验证 ---
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""

# --- SEO 优化配置 ---
[seo]
  # 默认的分享图片 URL
  image = ""
  # 默认的缩略图 URL
  thumbnailUrl = ""

# --- 网站分析工具 (如 Google Analytics) ---
[analytics]
  enable = false
  # Google Analytics
  [analytics.google]
    id = "" # 你的 GA ID
    # 是否匿名化 IP 地址
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    server = ""

# --- Cookie 授权弹窗 (GDPR 合规) ---
[cookieconsent]
  enable = false
  # 弹窗的文字内容
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# --- CDN 配置 ---
# 用于加载第三方库的 CDN 源
[cdn]
  # CDN 数据文件名，默认为空。可选 "jsdelivr.yml", "unpkg.yml" 等。
  # 可以在 "themes/FixIt/assets/data/cdn/" 目录下查看可用的 CDN 配置。
  data = ""

# --- 旧浏览器兼容性配置 ---
[compatibility]
  # 是否使用 Polyfill.io 兼容旧浏览器
  polyfill = false
  # 是否使用 object-fit-images 兼容旧浏览器
  objectFit = false

# --- GitHub 角标 ---
[githubCorner]
  # 是否在右上角显示一个指向 GitHub 仓库的角标。教程站强烈建议开启。
  enable = true
  # 你的 GitHub 仓库链接
  permalink = "https://github.com/ApolloMonasa/Minecraft-Modding-Tutorial-For-NeoForge"
  # 鼠标悬停时显示的文字
  title = "在 GitHub 上查看源码"
  # 显示位置 ["left", "right"]
  position = "right"

# --- Gravatar 头像配置 ---
[gravatar]
  # 是否启用 Gravatar 头像
  enable = false
  # Gravatar 服务器地址，建议使用国内镜像以加快加载速度。
  host = "cravatar.cn" # 可选: "gravatar.loli.net"
  # 默认头像样式，当邮箱没有注册 Gravatar 时显示
  style = "" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]

# --- "返回顶部" 按钮 ---
[backToTop]
  enable = true
  # 是否在按钮上显示滚动百分比
  scrollpercent = true

# --- 页面顶部阅读进度条 ---
[readingProgress]
  enable = true
  # 起始位置 ["left", "right"]
  start = "left"
  # 显示位置 ["top", "bottom"]
  position = "top"
  # 是否反向
  reversed = false
  # 亮色主题下的颜色
  light = ""
  # 暗色主题下的颜色
  dark = ""
  # 进度条高度
  height = "3px"

# --- 页面加载时的动画进度条 (Pace.js) ---
[pace]
  enable = true
  # 可用颜色
  # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
  color = "blue"
  # 可用主题样式
  # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", ... ]
  theme = "minimal"

# --- RSS 订阅源全局配置 ---
[feed]
  # RSS 源中包含的文章数量, -1 表示所有
  limit = 10
  # RSS 源中是否包含全文
  fullText = true
  # Follow.is 挑战
  [feed.follow]
    feedId = ""
    userId = ""

# --- 自定义 Partial (高级功能) ---
# 可以在网站的特定位置注入你自己的 HTML 代码片段。
[customPartials]
  head = [
    "inject/fixit-docs-bookmark.html",
  ]
  profile = []
  aside = []
  comment = []
  footer = []
  widgets = []
  assets = ['inject/fixitsdoc.html']
  postFooterBefore = []
  postFooterAfter = []

# --- 开发者选项 ---
[dev]
  enable = false
  # 检查主题更新
  c4u = false

# --- 文章页面 (Page) 的默认配置 ---
# 这里设置的值，可以在单篇文章的 Front Matter 中被覆盖。
[page]
  # 是否在文章作者旁显示头像。
  authorAvatar = true
  # 是否从首页的文章列表中隐藏此页面。
  hiddenFromHomePage = false
  # 是否从搜索结果中隐藏此页面。
  hiddenFromSearch = false
  # 是否从相关文章推荐中隐藏此页面。
  hiddenFromRelated = false
  # 是否从 RSS 源中隐藏此页面。
  hiddenFromFeed = false
  # 是否将 emoji 转换为 twemoji 图片。
  twemoji = false
  # 是否启用 lightgallery 图片灯箱效果（点击图片放大）。
  # 设置为 true, 图片需要有标题才能触发，如 ![alt](src "title")
  # 设置为 "force", 所有图片都会触发。教程站建议设为 true 或 "force"。
  lightgallery = true
  # 是否启用 Ruby 注音 (e.g. {ruby|furigana}) 扩展语法。
  ruby = true
  # 是否启用分数 (e.g. {1/2}) 扩展语法。
  fraction = true
  # 是否启用 Fontawesome (e.g. :fa-solid fa-fire:) 扩展语法。
  fontawesome = true
  # 文章底部的默认授权协议。
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # 是否显示“查看 Markdown 原文”的链接。
  linkToMarkdown = true
  # 是否显示“查看源码”链接（需要已配置 [gitInfo]）。
  linkToSource = true
  # 是否显示“编辑此页”链接（需要已配置 [gitInfo]）。
  linkToEdit = true
  # 是否显示“报告问题”链接（需要已配置 [gitInfo]）。
  linkToReport = true
  # 页面样式: "narrow" (窄), "normal" (普通), "wide" (宽)。
  pageStyle = "normal"
  # 是否自动记录并恢复阅读进度。
  autoBookmark = true
  # 是否显示字数统计。
  wordCount = true
  # 是否显示预计阅读时间。
  readingTime = true
  # 文章结束标记，会在文章末尾显示。
  endFlag = "---"
  # 是否启用 instant.page 预加载技术，加快页面跳转速度。
  instantPage = false
  # 是否在侧边栏显示系列文章列表。
  collectionList = false
  # 是否在文章末尾显示系列文章导航。
  collectionNavigation = false

  # 文章转载信息配置。
  [page.repost]
    enable = false
    url = ""
  # 文章目录 (TOC) 的默认设置。
  [page.toc]
    # 是否默认启用目录。
    enable = true
    # 是否在正文前也保留一份静态目录。
    keepStatic = false
    # 是否自动折叠侧边栏目录。
    auto = true
    # 目录显示在页面的哪个位置 ["left", "right"]。
    position = "right"
    # 是否给目录条目自动编号。
    ordered = false
    # 目录包含的标题起始级别 (e.g. h2)。
    startLevel = 2
    # 目录包含的标题结束级别 (e.g. h6)。
    endLevel = 6
  # 文章过期提醒。
  [page.expirationReminder]
    enable = true
    # 最后修改超过90天，显示提示。
    reminder = 90
    # 最后修改超过180天，显示警告。
    warning = 180
    # 如果文章过期，是否自动关闭评论。
    closeComment = false
  # 页面标题自动编号配置。
  [page.heading]
    # 是否将自动生成的文本（如章节号）首字母大写。
    capitalize = false
    # 必须将 page.toc.ordered 设置为 true 才生效。
    [page.heading.number]
      # 是否启用标题自动编号。
      enable = false
      # 是否只在主内容区（默认是 posts 目录）启用。
      onlyMainSection = true
      # 编号格式。
      [page.heading.number.format]
        h1 = "{title}"
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # KaTeX 数学公式支持。
  [page.math]
    enable = true
    # 行内公式的左右定界符。
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # 块级公式的左右定界符。
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # 是否启用 "复制公式" 功能。
    copyTex = true
    # 是否启用 mhchem 化学公式扩展。
    mhchem = true
  # 代码块的默认设置。
  [page.code]
    # 是否启用代码块的额外功能（复制按钮等）。
    enable = true
    # 是否显示“复制”按钮。
    copy = true
    # 是否显示“编辑”按钮，通常用于可交互的代码块，教程站可设为 false。
    edit = true
    # 默认最多显示多少行代码，超过的会折叠。
    maxShownLines = 10
  # Mapbox GL JS 地图配置。
  [page.mapbox]
    # Mapbox 的 access token。
    accessToken = ""
    # 亮色主题的地图样式。
    lightStyle = "mapbox://styles/mapbox/light-v11"
    # 暗色主题的地图样式。
    darkStyle = "mapbox://styles/mapbox/dark-v11"
    # ... 其他地图控件

  # [实验性功能] 缓存远程图片到本地。
  [page.cacheRemoteImages]
    enable = false
    # 是否将远程图片URL替换为本地URL。
    replace = false
  # 相关文章推荐。
  [page.related]
    enable = true
    count = 5
  # 文章底部的打赏功能。
  [page.reward]
    enable = false
    animation = false
    position = "after"
    # comment = "Buy me a coffee"
    mode = "static"
    # [page.reward.ways]
    #   wechatpay = "/images/wechatpay.png"
    #   alipay = "/images/alipay.png"

  # 文章底部的分享按钮。
  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = true
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false
  # --- 评论系统总开关 ---
  [page.comment]
    enable = true # 设为 true 以启用评论，并配置下面的具体服务。
    # Artalk 评论系统配置。
    [page.comment.artalk]
      enable = false
      server = "https://yourdomain"
      site = "默认站点"
      # ...
    # Disqus 评论系统配置。
    [page.comment.disqus]
      enable = false
      shortname = ""
    # Gitalk 评论系统配置。
    [page.comment.gitalk]
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine 评论系统配置。
    [page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      # ...
    # Waline 评论系统配置。
    [page.comment.waline]
      enable = false
      serverURL = ""
      # ...
    # Facebook 评论插件配置。
    [page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""
    # Telegram 评论插件配置。
    [page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      # ...
    # Comment 评论系统配置。
    [page.comment.comment]
      enable = false
    # Utterances 评论系统配置。
    [page.comment.utterances]
      enable = true
      repo = "ApolloMonasa/MyBlogComments"
      issueTerm = "pathname"
      theme = "github-light"
      label = "Comment"
      # ...
    # Twikoo 评论系统配置。
    [page.comment.twikoo]
      enable = false
      envId = ""
      # ...
    # --- Giscus 评论配置 (推荐！基于 GitHub Discussions) ---
    [page.comment.giscus]
      enable = false # 如果要用 Giscus，把这里设为 true
      # 你的 GitHub "用户名/仓库名"
      repo = "ApolloMonasa/Minecraft-Modding-Tutorial-For-NeoForge"
      # 从 Giscus 官网获取
      repoId = ""
      # 你在仓库 Discussions 中用于存放评论的分类名
      category = "Announcements"
      # 从 Giscus 官网获取
      categoryId = ""
      # 页面与 discussion 的映射方式
      mapping = "pathname"
      # 启用 Giscus 的 "Reactions" 功能
      reactionsEnabled = "1"
      emitMetadata = "0"
      # 评论框位置 ["top", "bottom"]
      inputPosition = "bottom"
      # 语言
      lang = "zh-CN"
      # 主题
      lightTheme = "light"
      darkTheme = "dark"
      # 是否延迟加载
      lazyLoad = true
  # 加载自定义的第三方库。
  [page.library]
    [page.library.css]
      # someCSS = "assets/css/_custom.scss"
    [page.library.js]
      #someJavascript = "/assets/js/custom.js"
  # 单个页面的 SEO 优化。
  [page.seo]
    # 此页面的分享图片。
    images = []
    # 发布者信息。
    [page.seo.publisher]
      name = ""
      logoUrl = ""
